apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-byfd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-byfd
    app.kubernetes.io/part-of: test-app-svfu
  name: test-component-byfd
  namespace: build-e2e-hacbs-otwi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-byfd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-byfd
    spec:
      containers:
      - image: quay.io/xinjiang/test-images:ea2a62bd13ee4296a0f678c91a3d4776
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
